### ISSUE TITLE
problem with heatmap of the trajectory and marker plots

### ISSUE THREAD

**Issue by alevigi** [KirstLab/asc_seurat#11]
Thank you so much for the nice tool. I'm having problems with the generation of the markers heatmap and the visualization of genes in the trajectory. The message below (the purple one int he right corner) says generating heatmap but the screen becomes dull and the heatmap doesn't appear. I have no problem at all with the generation of the trajectory. Any suggestions?
thank you in advance

**Comment by wendelljpereira** [comment]
Hi @alevigi, 

Thank you for using Asc-Seurat. Could you confirm if you are using the newest version (v2.1)? 

Also, are you loading a list of genes or defining the most important genes using dynverse, before starting the heatmap of the expression in the trajectory?

Based on your description, a possible problem could be the resources available to Docker. By default, Docker only allocates 2Gb of RAM from the total RAM available in your machine. The single-cell analysis is resource-consuming, and the amount of RAM required will also depend on the number of cells and complexity of your dataset. Have you adjusted the amount of RAM available to Docker?

**Comment by wendelljpereira** [comment]
Under "Containers / Apps" on the Docker's dashboard, you can see the container called "Asc_Seurat." If you click on the green icon (see the attached image), it will show the log files. The message at the end of the log file may help to track what happened.

![docker](https://user-images.githubusercontent.com/9042791/120384569-53e11200-c2f4-11eb-9adf-025fae6057f3.jpg)

**Comment by alevigi** [comment]
Thank you so much for your prompt reply. It was a memory problem indeed.

Now it works perfectly
