### ISSUE TITLE
data folder

### ISSUE THREAD

**Issue by midichlorian22** [KirstLab/asc_seurat#16]
Hi Wendel,
I am eager to try Asc-Seurat but I cannot figure out where the data folder is located on my computer :(.
Can you help?

**Comment by wendelljpereira** [comment]
Hi @midichlorian22, 

The data/ folder will be created in the same directory where you ran the docker command. Please, check the information here if you haven't done it yet: https://asc-seurat.readthedocs.io/en/latest/installation.html

So, let's say you just opened your terminal. You can use the command pwd to see what is your current directory. Then, you can create a new directory for your analysis using mkdir, and then move to it using cd commands (see below). Last, when you run the docker pull and docker run commands, the data/ folder will be created automatically. 

For example, when I open my terminal, I can run the following commands (in bold). If using a Windows machine, I recommend using the PowerShell terminal.

```
#shows my current working directory
pwd 
/Users/wendell/Desktop

# creates a new directory
mkdir my_single_cell 

# moves to the new directory
cd my_single_cell 

#shows my current working directory
pwd
/Users/wendellpereira/Desktop/my_single_cell

# Then, start the Docker run. Docker must be running on your computer before you execute this command.

docker pull kirstlab/asc_seurat && docker run -v "$(pwd):/app/user_work" -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp -d --name Asc_Seurat --rm -p 3838:3838 kirstlab/asc_seurat

#show the file and folder within my current directory. As you can see, the folder data/ was created. 
ls
RDS_files/ data/      www/
```


The next step is to open the browser in the localhost: http://localhost:3838/

I hope this information helps. Thank you for trying Asc-Seurat!

Cheers,
Wendell
